import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>BeenBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF"
          crossOrigin="anonymous"
        />
        <link
          href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
          rel="stylesheet"
        />
      </Head>

      <header className=" flex flex-row p-4 justify-between">
        <div>
          <Link href="/">
            <a className="btn btn-link">BeenBlog</a>
          </Link>
        </div>
        <div>
          <Link href="/introduce">
            <a className="btn btn-link">Introduce</a>
          </Link>

          <a href="#none" className="btn btn-link">
            Order
          </a>
          <a href="#none" className="btn btn-link">
            Hiring
          </a>
          <a href="#none" className="btn btn-link">
            Contact Us
          </a>
        </div>
      </header>
      <h1>BeenBlog</h1>
    </div>
  );
}
